name: Lint Markdown

on:
  push:
    branches-ignore:
      - main
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  setup-node-modules:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

  lint-md:
    name: Linting Markdown
    runs-on: ubuntu-latest
    needs: setup-node-modules
    steps:
      - name: Git Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Markdown Linting
        run: npm run lint-md
